### PR TITLE
fix: Create Policy and terms Pages

### PR DESCRIPTION
**Pull request by abhijeetw035**
## Overview

1. This PR fixes or fixes part of #106 .
2. This PR does the following: Created Private Policy page, Terms & Condition page and Refund/Cancellation Policy page.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

Screen Recording for PR: 

https://github.com/user-attachments/assets/3288aa06-1fa0-4832-9663-f7399e6ab4c1

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Pratik2026** [comment]
@abhijeetw035, download the image and add it to the assets folder instead of directly pasting the image URL.

**Comment by abhijeetw035** [comment]
@Pratik2026 made required changes

**Comment by Pratik2026** [comment]
@abhijeetw035, please resolve the merge conflict

**Comment by Pratik2026** [comment]
merged, thanks for your contribution @abhijeetw035

**Pull request merged**
