### PR TITLE
fix: created footer and pricing page layout

### PR DESCRIPTION
**Pull request by abhijeetw035**
## Overview

1. This PR fixes or fixes part of #101 .
2. This PR does the following: Adds a new Footer to the website.  Creates a new Pricing page.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/busify/assets/149177534/1f9a94e1-3739-4d0b-b50d-56e08c3e11c1

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Pratik2026** [comment]
@abhijeetw035 Nice work on the code! However, there are a few files/packages that have been mistakenly added/removed:

- The package-lock.json file is not supposed to be there in the root folder. Please delete it.
- You added the `@mui/joy` package in the frontend directory, but it's not used in your code. Let's remove it by running `npm uninstall @mui/joy` in the frontend directory.
- The `.env.template` files from both the frontend and backend directories have been deleted. These should be restored.

**Comment by abhijeetw035** [comment]
ok sir i will do the required.

**Comment by Pratik2026** [comment]
LGTM.

**Comment by Pratik2026** [comment]
merged, thanks for your contribution @abhijeetw035

**Comment by abhijeetw035** [comment]
Thank you sir @Pratik2026.

**Pull request merged**
