### PR TITLE
feat(encryption and decryption): added backend routes for ticket encryption and decryption

### PR DESCRIPTION
**Pull request by rohansen856**
…and decryption

## Overview

1. This PR fixes or fixes part of #95.
2. This PR does the following: added encryption and decryption rote in the backend for the ticket and also added a decryption route in the frontend for admin-only decryption.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/busify/assets/108976786/3bb07829-ca95-4551-8ead-881e55d34959

https://github.com/bsoc-bitbyte/busify/assets/108976786/b3af4993-cbdb-4dbc-9090-45391761df57

@Vaibhavsahu2810 please explain the details of this pr to @RISHIKESHk07 and @Pratik2026 

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Vaibhavsahu2810** [comment]
@RISHIKESHk07 and @Pratik2026 here is the details of the above pr
### Update Overview

This update introduces several key changes to the ticket handling process, including schema updates, service and controller modifications, and frontend adjustments. Below are the details:

#### Backend Changes:

1. **Ticket Schema Update:**
   - Added a new property `encryptedData` to the ticket schema to store the encrypted data.

2. **Service Update (`ticket.service.ts`):**
   - Implemented logic to generate an encrypted string containing the order ID and passenger emails.
   - Updated the ticket creation and management logic to utilize this encrypted string.

3. **Controller Update (`ticket.controller.ts`):**
   - Adjusted the controller methods to handle the new encrypted data format.

4. **New Backend Endpoint for Ticket Decryption:**
   - Created a new URL endpoint `/ticket-scanner` for decrypting ticket data.
   - Implemented decryption logic to retrieve and return the original ticket data (order ID, passenger emails, etc.) from the encrypted string.

#### Frontend Changes:

1. **Ticket Card Component:**
   - Modified the component to display the encrypted ticket data.

2. **Demo Page:**
   - Updated the demo page to include functionality for inputting an encrypted string and retrieving the original ticket data.

---

These changes enhance the security of ticket information by ensuring sensitive data is encrypted and decrypted as needed. The frontend updates provide a seamless user experience for interacting with encrypted ticket data.

Please review and merge these changes at your earliest convenience. Let me know if there are any questions or further adjustments needed.

---

**Comment by rohansen856** [comment]
# Division of work
As there are two contributors assigned to this issue, the work each contributor did is as follows:

Me, @rohansen856 mainly worked on the `encryption routes` and  @Vaibhavsahu2810 worked on `decryption routes`.

## files worked on
### @rohansen856  
- `backend/src/app.module.ts`
- `backend/prisma/schema.prisma`
- `backend/prisma/seed.mjs`
- `backend/src/ticket/ticket.service.ts`
- `frontend/src/components/TicketCard.tsx`

### @Vaibhavsahu2810 
- `backend/src/ticketScanner/ticket-scanner.controller.ts`
- `backend/src/ticketScanner/ticket-scanner.module.ts`
- `backend/src/ticketScanner/ticket-scanner.service.ts`
- `frontend/src/pages/DemoPage/demopage.tsx`

Thank you.

**Comment by RISHIKESHk07** [comment]
@rohansen856  some conflicts have occured please look in to

**Comment by rohansen856** [comment]
@RISHIKESHk07 @Pratik2026 we have solved all merge conflicts
 - updated the seeding file with some encrypted data
 - added encrypted data type in the `types` file

### working demo
https://github.com/bsoc-bitbyte/busify/assets/108976786/802d9ece-d317-4665-81db-5b0e82026500

please preview the changes and suggest any upgrades if necessary. thank you.

**Comment by RISHIKESHk07** [comment]
@rohansen856 @Vaibhavsahu2810 LGTM , @Pratik2026 any suggestions ? backend functions are straight forward , for UI we need to open a issue for creating a QR code ticket

**Comment by Pratik2026** [comment]
LGTM @Vaibhavsahu2810 @rohansen856, Nice work!

**Comment by Pratik2026** [comment]
merged, thank you for your patience and contributions, @rohansen856 and @Vaibhavsahu2810

**Comment by rohansen856** [comment]
> merged, thank you for your patience and contributions, @rohansen856 and @Vaibhavsahu2810

It was my pleasure. Thank you.

**Comment by Vaibhavsahu2810** [comment]
> merged, thank you for your patience and contributions, @rohansen856 and @Vaibhavsahu2810

I had fun and learned new things. I'm eager to tackle more issues like this in the future. Thank you!

**Pull request merged**
