### PR TITLE
fix #94 : Adds capabilities to create and update schedules. 

### LINKED ISSUE #94: [Feature Request]:  Implement the functionality to add new or edit existing bus schedule.
### Is your feature request related to a problem? Please describe.

As of now, the schedule page is completely hardcoded and the admin does not have any way to add or edit the bus schedule.

### Describe the solution you'd like

The following task is required to be completed to make the schedule page functional:
- Implement the modal to add and edit the bus schedule data according to the design which will open when the admin clicks on either the `add new` button or `queueCard`(dashed border one).
- Replace the see more text with edit text in both `BusCards` and `ConductorCards`, clicking on which same modal should be open but with existing data written in the fields.
- The admin must be able to add or update the bus schedule using that modal.
- On adding/updating the bus schedule, the schedule page should be rerendered to reflect the recent changes.

### Describe alternatives you've considered

_No response_

### Developer Help

- Here's the [Figma Design Link](https://www.figma.com/design/dhFhm64op9fcre1hbsGTab/Busify?node-id=282-686&t=LhHyoeafOMalYqZ7-0) for reference.
- In order to view the admin page as an "Admin" role, you can make a slight change in "frontend/src/store/ authstore.tsx" file:
At line 25 :
`setUser: user => set({ user: { ...user, role: 'admin', } }),`

### PR DESCRIPTION
**Pull request by Om-Thorat**
## Overview

1. This PR fixes or fixes part of #94 
2. This PR does the following: Adds capabilities to create and update schedules. 

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/busify/assets/76207818/e6c3c795-c47c-4cb8-b930-8c3633d8c4b5

## PR Pointers

- @Pratik2026 The design did not contain any ways to edit or adjust ticket price or checkpoints so those are hardcoded at the moment. 
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Om-Thorat** [comment]
https://github.com/bsoc-bitbyte/busify/assets/76207818/dbe2f834-f67e-434b-b860-20943f0761fe


* Added Checkpoints 
* Added bus choice

Made the bus choice field a drop down select. These values are hardcoded since there is no controller to get buses or a page to add buses. That implementation is out of scope for this PR. Create a separate issue for so.

**Comment by Om-Thorat** [comment]
@Pratik2026  The pr is ready for review

**Comment by Om-Thorat** [comment]
@Pratik2026 PTAL

**Comment by Pratik2026** [comment]
merged, thanks for your patience & contribution, @Om-Thorat

**Pull request merged**
