### PR TITLE
Fix #75: Added an admin page layout

### LINKED ISSUE #75: Create a AdminPageLayout component for admin pages.
### Is your feature request related to a problem? Please describe.

We will be having multiple pages involving the admin panel sidebar, a Navbar & a Footer as you can see in the below image. This will cause the redundancy in the codebase.

image

### Describe the solution you'd like

Create an `AdminPageLayout` component. The layout component is the wrapper that contains common components and wraps the different pages. You can learn more about this [here](https://chrisdevcode.hashnode.dev/how-to-create-a-layout-component-react)

### Describe alternatives you've considered

_No response_

### Developer Help

Both AdminSidebar & Footer have been created already. Include the Navbar code in the layout component itself. No need to create a separate navbar component as there's not much in it to do except a "Manage Buses" heading and day subheading (refer to the image).

### PR DESCRIPTION
**Pull request by Om-Thorat**
## Overview

1. This PR fixes or fixes part of #75 .
2. This PR does the following: 
* Creates an admin page layout so that the other pages can be made with reusable component.
*  Aligns all the contents in it within a grid to ensure responsiveness.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

image

image

image

## PR Pointers

* The footer currently isn't included in the Adminlayout, but i have left space for it if feasible during a future refactor of app.tsx needed to conditionally render the footer and navbar for admin layout differently.

### CODE REVIEW

**Comment by Pratik2026** [comment]
@Om-Thorat Nice work! so far the code looks clean to me.

About the footer and navbar, you can use the `useLocation` hook to conditionally render the already available navbar & footer on the basis of route(use `/adminpanel/component_name` route). This will allow you to incorporate different navbar for the admin pages.

**Comment by Om-Thorat** [comment]
Screenshots according to new commit.

image

image

image

**Comment by Pratik2026** [comment]
@Om-Thorat I can still see the `manage buses button` on the top right corner in the Navbar when navigating to the admin page as an "Admin" role but your screenshot indicates otherwise. 

image

**Comment by Pratik2026** [comment]
I think you have not set the conditional rendering on the `manage buses button`  since I can't see any changes made in that specific block of code.

**Comment by Om-Thorat** [comment]
> @Om-Thorat I can still see the `manage buses button` on the top right corner in the Navbar when navigating to the admin page as an "Admin" role but your screenshot indicates otherwise.
> 
> image

Might have been overlooked because of not having an admin role, will fix.

**Comment by Om-Thorat** [comment]
@Pratik2026 Pushed a commit Implementing the suggestion. The screenshots remain the same. PTAL

**Comment by Pratik2026** [comment]
@Om-Thorat LGTM.

**Comment by Pratik2026** [comment]
merged, thanks for contributing @Om-Thorat

**Pull request merged**
